spin_manifest_version = 2

[application]
name = "spin-otel-example"
version = "0.1.0"
authors = ["Local OTEL Team"]
description = "Example Spin app using OpenTelemetry component"

[[trigger.http]]
route = "/..."
component = "http-handler"

[component.http-handler]
source = "main.wasm"
allowed_outbound_hosts = ["http://localhost:4318", "http://host.docker.internal:4318"]

[component.http-handler.build]
command = "make build"

# Component dependencies
[component.http-handler.dependencies]
"local:otel/telemetry" = { path = "../otel-component.wasm" }
