version: '3.8'

services:
  wasm-otel-collector:
    image: otel/opentelemetry-collector-contrib:0.91.0
    container_name: wasm-otel-collector
    command: ["--config=/etc/otel-collector-config.yaml"]
    volumes:
      - ./configs/wasm-collector.yaml:/etc/otel-collector-config.yaml
      - ./data/wasm:/data/wasm
    ports:
      - "4317:4317"   # OTLP gRPC
      - "4318:4318"   # OTLP HTTP
      - "8888:8888"   # Prometheus metrics
    environment:
      - LOG_LEVEL=debug
    networks:
      - wasm-otel

networks:
  wasm-otel:
    driver: bridge
