version: '3.8'

services:
  # ============== EXISTING SERVICES ==============
  # OpenTelemetry Collector (Enhanced for dual export)
  otel-collector:
    image: otel/opentelemetry-collector-contrib:latest
    container_name: telemetry-nest-otel-collector
    command: ["--config=/etc/otel-collector-config.yaml"]
    volumes:
      - ./docker/configs/otel/otel-collector-config-signoz.yaml:/etc/otel-collector-config.yaml
      - ./data:/data
    ports:
      - "4317:4317"   # OTLP gRPC receiver
      - "4318:4318"   # OTLP HTTP receiver
      - "13133:13133" # Health check extension
      - "8889:8889"   # Prometheus metrics endpoint
    networks:
      - telemetry-network
    depends_on:
      - prometheus
      - signoz-otel-collector
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:13133/"]
      interval: 30s
      timeout: 10s
      retries: 3

  # StatsD Server
  statsd:
    image: statsd/statsd:latest
    container_name: telemetry-nest-statsd
    volumes:
      - ./docker/configs/statsd/config.js:/usr/src/app/config.js
      - ./data/metrics:/data/metrics
    ports:
      - "8125:8125/udp"
      - "8126:8126"   # Admin interface
    networks:
      - telemetry-network
    restart: unless-stopped
    environment:
      - STATSD_CONFIG_FILE=/usr/src/app/config.js

  # Prometheus
  prometheus:
    image: prom/prometheus:latest
    container_name: telemetry-nest-prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/etc/prometheus/console_libraries'
      - '--web.console.templates=/etc/prometheus/consoles'
      - '--storage.tsdb.retention.time=7d'
      - '--web.enable-lifecycle'
    volumes:
      - ./docker/configs/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus-data:/prometheus
    ports:
      - "9090:9090"
    networks:
      - telemetry-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:9090/-/healthy"]
      interval: 30s
      timeout: 10s
      retries: 3

  # Grafana
  grafana:
    image: grafana/grafana:latest
    container_name: telemetry-nest-grafana
    volumes:
      - grafana-data:/var/lib/grafana
      - ./docker/configs/grafana/provisioning:/etc/grafana/provisioning
      - ./docker/configs/grafana/dashboards:/var/lib/grafana/dashboards
    ports:
      - "3000:3000"
    networks:
      - telemetry-network
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
      - GF_USERS_ALLOW_SIGN_UP=false
      - GF_INSTALL_PLUGINS=grafana-piechart-panel
    depends_on:
      - prometheus
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:3000/api/health || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3

  # Jaeger (for trace visualization)
  jaeger:
    image: jaegertracing/all-in-one:latest
    container_name: telemetry-nest-jaeger
    ports:
      - "16686:16686" # Jaeger UI
      - "14250:14250" # gRPC
    networks:
      - telemetry-network
    environment:
      - COLLECTOR_OTLP_ENABLED=true
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:16686/"]
      interval: 30s
      timeout: 10s
      retries: 3

  # Filebeat (for log processing)
  filebeat:
    image: elastic/filebeat:8.11.0
    container_name: telemetry-nest-filebeat
    user: root
    volumes:
      - ./docker/configs/filebeat/filebeat.yml:/usr/share/filebeat/filebeat.yml:ro
      - ./data:/data
      - /var/lib/docker/containers:/var/lib/docker/containers:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
    networks:
      - telemetry-network
    depends_on:
      - otel-collector
    restart: unless-stopped
    command: filebeat -e -strict.perms=false

  # ============== SIGNOZ SERVICES ==============
  # SigNoz ClickHouse Database
  signoz-clickhouse:
    image: clickhouse/clickhouse-server:24.1.2-alpine
    container_name: signoz-clickhouse
    hostname: clickhouse
    volumes:
      - signoz-clickhouse-data:/var/lib/clickhouse
      - ./docker/configs/signoz/clickhouse-config.xml:/etc/clickhouse-server/config.xml
      - ./docker/configs/signoz/clickhouse-users.xml:/etc/clickhouse-server/users.xml
      - ./docker/configs/signoz/clickhouse-storage.xml:/etc/clickhouse-server/config.d/storage.xml
    environment:
      - CLICKHOUSE_DB=signoz_traces
      - CLICKHOUSE_USER=signoz
      - CLICKHOUSE_PASSWORD=signoz
      - CLICKHOUSE_DEFAULT_ACCESS_MANAGEMENT=1
    ports:
      - "9000:9000"
      - "8123:8123"
    networks:
      - telemetry-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "clickhouse-client", "-q", "SELECT 1"]
      interval: 30s
      timeout: 5s
      retries: 3

  # SigNoz OpenTelemetry Collector
  signoz-otel-collector:
    image: signoz/signoz-otel-collector:0.88.11
    container_name: signoz-otel-collector
    command: ["--config=/etc/otel/config.yaml"]
    volumes:
      - ./docker/configs/signoz/otel-collector-config.yaml:/etc/otel/config.yaml
    environment:
      - OTEL_RESOURCE_ATTRIBUTES=host.name=signoz-collector,os.type=linux
      - CLICKHOUSE_HOST=clickhouse
      - CLICKHOUSE_PORT=9000
      - CLICKHOUSE_USER=signoz
      - CLICKHOUSE_PASSWORD=signoz
      - CLICKHOUSE_DATABASE=signoz_traces
    ports:
      - "4327:4317"   # OTLP gRPC receiver for SigNoz
      - "4328:4318"   # OTLP HTTP receiver for SigNoz
    networks:
      - telemetry-network
    depends_on:
      signoz-clickhouse:
        condition: service_healthy
    restart: unless-stopped

  # SigNoz Query Service
  signoz-query-service:
    image: signoz/query-service:0.41.1
    container_name: signoz-query-service
    command: ["-config=/root/config/prometheus.yml"]
    volumes:
      - ./docker/configs/signoz/prometheus.yml:/root/config/prometheus.yml
      - signoz-dashboards:/root/config/dashboards
      - signoz-data:/var/lib/signoz
    environment:
      - ClickHouseUrl=tcp://clickhouse:9000
      - CLICKHOUSE_USER=signoz
      - CLICKHOUSE_PASSWORD=signoz
      - ALERTMANAGER_API_PREFIX=http://alertmanager:9093/api/
      - SIGNOZ_LOCAL_DB_PATH=/var/lib/signoz/signoz.db
      - DASHBOARDS_PATH=/root/config/dashboards
      - STORAGE=clickhouse
      - GODEBUG=netdns=go
      - TELEMETRY_ENABLED=false
    ports:
      - "8080:8080"
    networks:
      - telemetry-network
    depends_on:
      signoz-clickhouse:
        condition: service_healthy
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "--spider", "-q", "localhost:8080/api/v1/health"]
      interval: 30s
      timeout: 5s
      retries: 3

  # SigNoz Frontend
  signoz-frontend:
    image: signoz/frontend:0.41.1
    container_name: signoz-frontend
    environment:
      - FRONTEND_API_URL=http://signoz-query-service:8080
    ports:
      - "3301:3301"
    networks:
      - telemetry-network
    depends_on:
      - signoz-query-service
    restart: unless-stopped

  # SigNoz AlertManager
  signoz-alertmanager:
    image: signoz/alertmanager:0.23.5
    container_name: signoz-alertmanager
    volumes:
      - signoz-alertmanager-data:/data
    ports:
      - "9093:9093"
    networks:
      - telemetry-network
    restart: unless-stopped
    command:
      - --config.file=/etc/alertmanager/alertmanager.yml
      - --storage.path=/data

networks:
  telemetry-network:
    external: true
    name: telemetry-nest-network

volumes:
  prometheus-data:
    name: telemetry-nest-prometheus-data
  grafana-data:
    name: telemetry-nest-grafana-data
  signoz-clickhouse-data:
    name: signoz-clickhouse-data
  signoz-dashboards:
    name: signoz-dashboards
  signoz-data:
    name: signoz-data
  signoz-alertmanager-data:
    name: signoz-alertmanager-data
