version: '3.8'

services:
  canary-api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: canary-api
    ports:
      - "8000:8000"
    environment:
      # Service configuration
      SERVICE_NAME: canary-api
      SERVICE_VERSION: 1.0.0
      
      # OpenTelemetry configuration
      OTLP_ENDPOINT: http://telemetry-nest-otel-collector:4318/v1/traces
      OTEL_SERVICE_NAME: canary-api
      OTEL_SERVICE_VERSION: 1.0.0
      OTEL_EXPORTER_OTLP_ENDPOINT: http://telemetry-nest-otel-collector:4318
      OTEL_EXPORTER_OTLP_PROTOCOL: http/protobuf
      
      # StatsD configuration
      STATSD_HOST: telemetry-nest-statsd
      STATSD_PORT: 8125
      
      # Logging configuration
      LOG_LEVEL: INFO
      
      # Development settings
      RELOAD: "false"
      
    volumes:
      # Mount logs directory for file-based logging (optional)
      - ../../data/logs:/app/logs
      
    networks:
      - telemetry-nest
      
    depends_on:
      - telemetry-check
      
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/chirp"]
      interval: 30s
      timeout: 3s
      retries: 3
      start_period: 10s
      
    restart: unless-stopped
    
  # Service to verify telemetry stack is running
  telemetry-check:
    image: curlimages/curl:8.4.0
    command: |
      sh -c '
        until curl -f http://telemetry-nest-otel-collector:13133/ 2>/dev/null; do
          echo "Waiting for OpenTelemetry Collector..."
          sleep 2
        done
        echo "Telemetry stack is ready!"
      '
    networks:
      - telemetry-nest
    restart: "no"

# Use the external network from the main telemetry stack
networks:
  telemetry-nest:
    external: true
