global:
  scrape_interval: 15s
  evaluation_interval: 15s
  external_labels:
    environment: 'local-development'
    project: 'canary-api'

rule_files:
  # - "first_rules.yml"
  # - "second_rules.yml"

scrape_configs:
  # OpenTelemetry Collector metrics
  - job_name: 'otel-collector'
    static_configs:
      - targets: ['otel-collector:8889']
    scrape_interval: 10s
    metrics_path: /metrics
    
  # Prometheus self-monitoring
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']
    scrape_interval: 30s

  # Application server metrics (when available)
  - job_name: 'canary-api-server'
    static_configs:
      - targets: ['host.docker.internal:9464']  # Default application metrics port
    scrape_interval: 10s
    metrics_path: /metrics
    scrape_timeout: 5s
    # Only scrape if application server is running with metrics enabled
    honor_labels: true
    
  # StatsD exporter metrics (if using prometheus-statsd-exporter)
  - job_name: 'statsd-exporter'
    static_configs:
      - targets: ['statsd:9102']
    scrape_interval: 10s
    metrics_path: /metrics
    scrape_timeout: 5s

  # Container metrics (cAdvisor if available)
  - job_name: 'cadvisor'
    static_configs:
      - targets: ['cadvisor:8080']
    scrape_interval: 30s
    metrics_path: /metrics
    scrape_timeout: 10s

# Alerting configuration (for development)
alerting:
  alertmanagers:
    - static_configs:
        - targets:
          # - alertmanager:9093

# Storage configuration is handled via command-line arguments in docker-compose.yml
# --storage.tsdb.retention.time=7d
# --storage.tsdb.retention.size=1GB
    
# Remote write configuration (for future cloud integration)
# remote_write:
#   - url: "https://your-cloud-provider/api/v1/write"
#     basic_auth:
#       username: "your-username"
#       password: "your-password"

# Remote read configuration (for future cloud integration)
# remote_read:
#   - url: "https://your-cloud-provider/api/v1/read"
#     basic_auth:
#       username: "your-username"
#       password: "your-password"
