// Code generated by wit-bindgen-go. DO NOT EDIT.

package telemetry

import (
	"go.bytecodealliance.org/cm"
)

func lift_ProviderConfig(f0 *uint8, f1 uint32, f2 *uint8, f3 uint32, f4 uint32) (v ProviderConfig) {
	v.Endpoint = cm.LiftString[string](f0, f1)
	v.ServiceName = cm.LiftString[string](f2, f3)
	v.DevMode = (bool)(cm.U32ToBool(f4))
	return
}

func lift_LogRecord(f0 *uint8, f1 uint32, f2 uint32) (v LogRecord) {
	v.Body = cm.LiftString[string](f0, f1)
	v.Severity = (SeverityLevel)(f2)
	return
}
