// Code generated by wit-bindgen-go. DO NOT EDIT.

package telemetry

import (
	"go.bytecodealliance.org/cm"
)

// This file contains wasmimport and wasmexport declarations for "local:otel".

//go:wasmimport [export]local:otel/telemetry [resource-new]telemetry-provider
//go:noescape
func wasmimport_TelemetryProviderResourceNew(rep0 uint32) (result0 uint32)

//go:wasmimport [export]local:otel/telemetry [resource-rep]telemetry-provider
//go:noescape
func wasmimport_TelemetryProviderResourceRep(self0 uint32) (result0 uint32)

//go:wasmimport [export]local:otel/telemetry [resource-drop]telemetry-provider
//go:noescape
func wasmimport_TelemetryProviderResourceDrop(self0 uint32)

//go:wasmexport local:otel/telemetry#[dtor]telemetry-provider
//export local:otel/telemetry#[dtor]telemetry-provider
func wasmexport_TelemetryProviderDestructor(self0 uint32) {
	self := cm.Reinterpret[cm.Rep]((uint32)(self0))
	Exports.TelemetryProvider.Destructor(self)
	return
}

//go:wasmexport local:otel/telemetry#[constructor]telemetry-provider
//export local:otel/telemetry#[constructor]telemetry-provider
func wasmexport_Constructor(config0 *uint8, config1 uint32, config2 *uint8, config3 uint32, config4 uint32) (result0 uint32) {
	config := lift_ProviderConfig((*uint8)(config0), (uint32)(config1), (*uint8)(config2), (uint32)(config3), (uint32)(config4))
	result := Exports.TelemetryProvider.Constructor(config)
	result0 = cm.Reinterpret[uint32](result)
	return
}

//go:wasmexport local:otel/telemetry#[method]telemetry-provider.create-logger
//export local:otel/telemetry#[method]telemetry-provider.create-logger
func wasmexport_TelemetryProviderCreateLogger(self0 uint32, name0 *uint8, name1 uint32) (result *cm.Result[string, Logger, string]) {
	self := cm.Reinterpret[cm.Rep]((uint32)(self0))
	name := cm.LiftString[string]((*uint8)(name0), (uint32)(name1))
	result_ := Exports.TelemetryProvider.CreateLogger(self, name)
	result = &result_
	return
}

//go:wasmimport [export]local:otel/telemetry [resource-new]logger
//go:noescape
func wasmimport_LoggerResourceNew(rep0 uint32) (result0 uint32)

//go:wasmimport [export]local:otel/telemetry [resource-rep]logger
//go:noescape
func wasmimport_LoggerResourceRep(self0 uint32) (result0 uint32)

//go:wasmimport [export]local:otel/telemetry [resource-drop]logger
//go:noescape
func wasmimport_LoggerResourceDrop(self0 uint32)

//go:wasmexport local:otel/telemetry#[dtor]logger
//export local:otel/telemetry#[dtor]logger
func wasmexport_LoggerDestructor(self0 uint32) {
	self := cm.Reinterpret[cm.Rep]((uint32)(self0))
	Exports.Logger.Destructor(self)
	return
}

//go:wasmexport local:otel/telemetry#[method]logger.emit
//export local:otel/telemetry#[method]logger.emit
func wasmexport_LoggerEmit(self0 uint32, log0 *uint8, log1 uint32, log2 uint32) (result *cm.Result[string, struct{}, string]) {
	self := cm.Reinterpret[cm.Rep]((uint32)(self0))
	log := lift_LogRecord((*uint8)(log0), (uint32)(log1), (uint32)(log2))
	result_ := Exports.Logger.Emit(self, log)
	result = &result_
	return
}
