// Code generated by wit-bindgen-go. DO NOT EDIT.

package telemetry

import (
	"go.bytecodealliance.org/cm"
)

// Exports represents the caller-defined exports from "local:otel/telemetry".
var Exports struct {
	// TelemetryProvider represents the caller-defined exports for resource "local:otel/telemetry#telemetry-provider".
	TelemetryProvider struct {
		// Destructor represents the caller-defined, exported destructor for resource "telemetry-provider".
		//
		// Resource destructor.
		Destructor func(self cm.Rep)

		// Constructor represents the caller-defined, exported constructor for resource "telemetry-provider".
		//
		//	constructor(config: provider-config)
		Constructor func(config ProviderConfig) (result TelemetryProvider)

		// CreateLogger represents the caller-defined, exported method "create-logger".
		//
		//	create-logger: func(name: string) -> result<logger, string>
		CreateLogger func(self cm.Rep, name string) (result cm.Result[string, Logger, string])
	}

	// Logger represents the caller-defined exports for resource "local:otel/telemetry#logger".
	Logger struct {
		// Destructor represents the caller-defined, exported destructor for resource "logger".
		//
		// Resource destructor.
		Destructor func(self cm.Rep)

		// Emit represents the caller-defined, exported method "emit".
		//
		//	emit: func(log: log-record) -> result<_, string>
		Emit func(self cm.Rep, log LogRecord) (result cm.Result[string, struct{}, string])
	}
}
