global:
  evaluation_interval: 30s
  scrape_interval: 30s

rule_files:
  - /root/config/alerting_rules.yml

remote_write:
  - url: http://localhost:8080/api/v1/write

scrape_configs:
  - job_name: signoz-metrics
    static_configs:
      - targets:
          - signoz-otel-collector:8889
