receivers:
  otlp:
    protocols:
      grpc:
        endpoint: localhost:4317
      http:
        endpoint: localhost:4318
  
  # Prometheus receiver for local WASM metrics
  prometheus:
    config:
      scrape_configs:
        - job_name: 'wasm-local-dev'
          scrape_interval: 15s
          static_configs:
            - targets: ['localhost:3001']  # WASM dev server metrics
          metric_relabel_configs:
            - source_labels: [__name__]
              regex: 'wasm_.*'
              action: keep

processors:
  batch:
    timeout: 1s
    send_batch_size: 1024
  
  attributes:
    actions:
      - key: service.namespace
        value: wasm-dev
        action: insert
      - key: deployment.environment
        value: local
        action: insert
  
  resource:
    attributes:
      - key: host.name
        value: localhost
        action: insert

exporters:
  file/metrics:
    path: ./data/wasm/metrics.jsonl
  
  file/traces:
    path: ./data/wasm/traces.jsonl
  
  file/logs:
    path: ./data/wasm/logs.jsonl
  
  logging:
    loglevel: debug
    sampling_initial: 5
    sampling_thereafter: 200

service:
  pipelines:
    metrics:
      receivers: [prometheus, otlp]
      processors: [batch, attributes, resource]
      exporters: [file/metrics, logging]
    
    traces:
      receivers: [otlp]
      processors: [batch, attributes, resource]
      exporters: [file/traces, logging]
    
    logs:
      receivers: [otlp]
      processors: [batch, attributes, resource]
      exporters: [file/logs, logging]
