version: '3.8'

services:
  # Frontend - SvelteKit with SSR
  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
      - PUBLIC_API_URL=http://localhost:8080
      - PUBLIC_WS_URL=ws://localhost:8080
      - OTEL_SERVICE_NAME=social-media-frontend
      - OTEL_EXPORTER_OTLP_ENDPOINT=http://otel-collector:4318
    depends_on:
      - auth-service
      - user-profile-service
      - feed-service
      - messaging-service
    volumes:
      - ./frontend:/app
      - /app/node_modules
    networks:
      - social-media-net
      - telemetry-net

  # API Gateway / Load Balancer
  nginx:
    image: nginx:alpine
    ports:
      - "8080:80"
    volumes:
      - ./infrastructure/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - auth-service
      - user-profile-service
      - feed-service
      - messaging-service
      - media-service
    networks:
      - social-media-net

  # Auth Service - Node.js with OAuth
  auth-service:
    build: ./auth-service
    environment:
      - NODE_ENV=development
      - PORT=3001
      - DATABASE_URL=postgresql://user:password@auth-db:5432/auth
      - REDIS_URL=redis://auth-redis:6379
      - JWT_SECRET=your-jwt-secret-here
      - GOOGLE_CLIENT_ID=your-google-client-id
      - GOOGLE_CLIENT_SECRET=your-google-client-secret
      - GITHUB_CLIENT_ID=your-github-client-id
      - GITHUB_CLIENT_SECRET=your-github-client-secret
      - OTEL_SERVICE_NAME=auth-service
      - OTEL_EXPORTER_OTLP_ENDPOINT=http://otel-collector:4318
      - STATSD_HOST=statsd
      - STATSD_PORT=8125
    depends_on:
      - auth-db
      - auth-redis
    networks:
      - social-media-net
      - telemetry-net

  # User Profile Service - Python FastAPI
  user-profile-service:
    build: ./user-profile-service
    environment:
      - DATABASE_URL=postgresql://user:password@user-db:5432/profiles
      - REDIS_URL=redis://profile-redis:6379
      - SERVICE_NAME=user-profile-service
      - OTLP_ENDPOINT=http://otel-collector:4318/v1/traces
      - STATSD_HOST=statsd
      - STATSD_PORT=8125
    depends_on:
      - user-db
      - profile-redis
    networks:
      - social-media-net
      - telemetry-net

  # Feed Service - Go with Gin
  feed-service:
    build: ./feed-service
    environment:
      - DATABASE_URL=postgres://user:password@feed-db:5432/feed?sslmode=disable
      - REDIS_URL=redis://feed-redis:6379
      - MEDIA_SERVICE_URL=http://media-service:3005
      - USER_SERVICE_URL=http://user-profile-service:8000
      - OTEL_SERVICE_NAME=feed-service
      - OTEL_EXPORTER_OTLP_ENDPOINT=http://otel-collector:4318
      - STATSD_HOST=statsd
      - STATSD_PORT=8125
    depends_on:
      - feed-db
      - feed-redis
    networks:
      - social-media-net
      - telemetry-net

  # Messaging Service - Node.js with WebSocket
  messaging-service:
    build: ./messaging-service
    environment:
      - NODE_ENV=development
      - PORT=3004
      - DATABASE_URL=postgresql://user:password@messages-db:5432/messages
      - REDIS_URL=redis://messages-redis:6379
      - AUTH_SERVICE_URL=http://auth-service:3001
      - OTEL_SERVICE_NAME=messaging-service
      - OTEL_EXPORTER_OTLP_ENDPOINT=http://otel-collector:4318
      - STATSD_HOST=statsd
      - STATSD_PORT=8125
    depends_on:
      - messages-db
      - messages-redis
    networks:
      - social-media-net
      - telemetry-net

  # Media Service - Rust with Actix
  media-service:
    build: ./media-service
    environment:
      - MINIO_ENDPOINT=minio:9000
      - MINIO_ACCESS_KEY=minioadmin
      - MINIO_SECRET_KEY=minioadmin
      - MINIO_BUCKET=social-media
      - SERVICE_NAME=media-service
      - OTEL_EXPORTER_OTLP_ENDPOINT=http://otel-collector:4318
      - STATSD_HOST=statsd
      - STATSD_PORT=8125
    depends_on:
      - minio
    networks:
      - social-media-net
      - telemetry-net

  # Mobile Simulator
  mobile-simulator:
    build: ./mobile-simulator
    environment:
      - API_BASE_URL=http://nginx:80
      - SCENARIOS=new_user,active_user,influencer
      - SIMULATION_RATE=medium
      - OTEL_SERVICE_NAME=mobile-simulator
      - OTEL_EXPORTER_OTLP_ENDPOINT=http://otel-collector:4318
    depends_on:
      - nginx
      - frontend
    networks:
      - social-media-net
      - telemetry-net

  # Databases
  auth-db:
    image: postgres:15-alpine
    environment:
      - POSTGRES_DB=auth
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
    volumes:
      - auth-db-data:/var/lib/postgresql/data
    networks:
      - social-media-net

  user-db:
    image: postgres:15-alpine
    environment:
      - POSTGRES_DB=profiles
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
    volumes:
      - user-db-data:/var/lib/postgresql/data
    networks:
      - social-media-net

  feed-db:
    image: postgres:15-alpine
    environment:
      - POSTGRES_DB=feed
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
    volumes:
      - feed-db-data:/var/lib/postgresql/data
    networks:
      - social-media-net

  messages-db:
    image: postgres:15-alpine
    environment:
      - POSTGRES_DB=messages
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
    volumes:
      - messages-db-data:/var/lib/postgresql/data
    networks:
      - social-media-net

  # Redis Instances
  auth-redis:
    image: redis:7-alpine
    command: redis-server --maxmemory 256mb --maxmemory-policy allkeys-lru
    networks:
      - social-media-net

  profile-redis:
    image: redis:7-alpine
    command: redis-server --maxmemory 256mb --maxmemory-policy allkeys-lru
    networks:
      - social-media-net

  feed-redis:
    image: redis:7-alpine
    command: redis-server --maxmemory 512mb --maxmemory-policy allkeys-lru
    networks:
      - social-media-net

  messages-redis:
    image: redis:7-alpine
    command: redis-server --pubsubclient-output-buffer-limit "normal 0 0 0 slave 268435456 67108864 60 pubsub 0 0 0"
    networks:
      - social-media-net

  # MinIO Object Storage
  minio:
    image: minio/minio:latest
    command: server /data --console-address ":9001"
    environment:
      - MINIO_ROOT_USER=minioadmin
      - MINIO_ROOT_PASSWORD=minioadmin
    ports:
      - "9001:9001"  # MinIO Console
    volumes:
      - minio-data:/data
    networks:
      - social-media-net

  # Initialize MinIO buckets
  minio-init:
    image: minio/mc:latest
    depends_on:
      - minio
    entrypoint: >
      /bin/sh -c "
      /usr/bin/mc config host add myminio http://minio:9000 minioadmin minioadmin;
      /usr/bin/mc mb -p myminio/social-media;
      /usr/bin/mc anonymous set public myminio/social-media;
      exit 0;
      "
    networks:
      - social-media-net

volumes:
  auth-db-data:
  user-db-data:
  feed-db-data:
  messages-db-data:
  minio-data:

networks:
  social-media-net:
    driver: bridge
  telemetry-net:
    external: true
    name: local-otel_default
